# Generated by Django 3.2.3 on 2021-05-23 19:23

from django.db import migrations, models
import django.db.models.deletion
import planner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(validators=[planner.models.check_timezone])),
                ('average_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(validators=[planner.models.check_timezone])),
            ],
        ),
        migrations.CreateModel(
            name='EnergyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(unique=True, validators=[planner.models.check_timezone])),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarChargingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(validators=[planner.models.check_timezone])),
                ('stop_time', models.DateTimeField(validators=[planner.models.check_timezone])),
                ('start_task_id', models.TextField()),
                ('stop_task_id', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.carchargingsession')),
            ],
        ),
    ]
