# Generated by Django 3.2.3 on 2021-05-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carchargingsession',
            name='scheduled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
