# Generated by Django 3.2.3 on 2021-06-03 18:41

from django.db import migrations, models
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_carchargingsession_scheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField(unique=True)),
                ('hw_nest_override', models.BooleanField()),
                ('hw_elec_heater_on', models.BooleanField()),
                ('hw_gas_heater_on', models.BooleanField()),
                ('ev_charge_override', models.BooleanField()),
                ('ev_charging', models.BooleanField()),
                ('ev_soc', models.IntegerField()),
                ('ev_last_updated', models.DateTimeField(validators=[planner.models.check_timezone])),
            ],
        ),
    ]
