# Generated by Django 3.2.3 on 2021-08-07 19:20

from django.db import migrations, models
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_systemstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterHeatingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elec_heating', models.BooleanField()),
                ('start_time', models.DateTimeField(validators=[planner.models.check_timezone])),
                ('stop_time', models.DateTimeField(validators=[planner.models.check_timezone])),
                ('start_task_id', models.TextField()),
                ('stop_task_id', models.TextField()),
            ],
        ),
    ]
